package algorithms;

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

 */

import com.sun.xml.internal.fastinfoset.util.CharArray;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class FindDifference {
    public char findTheDifference(String s, String t) {
        char[] arr1= s.toCharArray();
        char[] arr2=t.toCharArray();
        Arrays.sort(arr1);
        Arrays.sort(arr2);

        for(int i=0; i<arr1.length; i++){
            if(arr1[i]!=arr2[i]) return arr2[i];
        }
        return arr2[arr2.length-1];
    }
    public static void main(String args[]){
        FindDifference findDifference=new FindDifference();
        char result=findDifference.findTheDifference("abcd", "cdaeb");
        System.out.println(result);
    }
}
